trigger:
- dev

variables:
  azureSubscription: 'Azure for Students (a428c075-d253-4045-ad71-30fc90d3c209)'
  functionAppName: 'preprodfuncappgroupedeuxb2'
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/AzureFunctionEFCore/SecurityServer.Function'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(workingDirectory)/*.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release
    
    # - task: DotNetCoreCLI@2
    #   displayName: 'Install dotnet-ef'
    #   inputs:
    #     command: 'custom'
    #     custom: 'tool'
    #     arguments: 'install --global dotnet-ef'

    # - task: DotNetCoreCLI@2
    #   inputs:
    #     command: 'custom'
    #     projects: '**/SecurityServer.DataAccess.csproj'
    #     custom: 'ef'
    #     arguments: migrations script -o $(Build.ArtifactStagingDirectory)/migrations/scripts.sql -v -i

    # - task: DotNetCoreCLI@2
    #   inputs:
    #     command: 'custom'
    #     projects: '**/*.csproj'
    #     custom: 'dotnet ef database update'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/*.csproj'
        arguments: '--output $(System.DefaultWorkingDirectory)/publish_output --configuration Release'
    
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildNumber).zip
      artifact: drop

# - stage: Deploy
#   displayName: Deploy stage
#   dependsOn: Build
#   condition: succeeded()

#   jobs:
#   - deployment: Deploy
#     displayName: Deploy
#     environment: 'development'
#     pool:
#       vmImage: $(vmImageName)

#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - task: AzureFunctionApp@1
#             displayName: 'Azure functions app deploy'
#             inputs:
#               azureSubscription: '$(azureSubscription)'
#               appType: functionApp
#               appName: $(functionAppName)
#               package: '$(Pipeline.Workspace)/drop/$(Build.BuildNumber).zip'
